import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { tv, defaultConfig } from "tailwind-variants";
import Providers from "@/libs/Providers";
import "react-day-picker/style.css";
import "./globals.css";
import { Toaster } from "@/components/shadcn/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: ["400", "500", "600", "700"],
  fallback: ["sans-serif"],
});

const bodyStyles = tv({
  base: "text-dark-1 bg-white",
});

defaultConfig.twMergeConfig = {
  ...defaultConfig.twMergeConfig,
  classGroups: {
    "text-brand": [
      "text-brand-main",
      "text-brand-secondary",
      "text-brand-accent",
    ],
    "text-heading": [
      "text-heading-1",
      "text-heading-2",
      "text-heading-3",
      "text-heading-4",
      "text-heading-5",
      "text-heading-6",
    ],
    "text-body": ["text-body-large", "text-body-normal", "text-body-small"],
    "text-dark": ["text-dark-1", "text-dark-2", "text-dark-3"],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.variable} ${bodyStyles()}`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
